### ISSUE TITLE
Crash on injection button clicked 

### ISSUE THREAD

**Issue by UxHarshit** [reveny/Android-GUI-Injector#25]
When I click on inject button it crashes.

**Crash log** 
```
time: 1725174498042
msg: java.lang.SecurityException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14499)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2666)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2844)
	at android.os.Binder.execTransactInternal(Binder.java:1500)
	at android.os.Binder.execTransact(Binder.java:1444)

stacktrace: java.lang.SecurityException: io.github.reveny.injector: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3187)
	at android.os.Parcel.createException(Parcel.java:3171)
	at android.os.Parcel.readException(Parcel.java:3154)
	at android.os.Parcel.readException(Parcel.java:3096)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5895)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1853)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1793)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1781)
	at z0.t.r(SourceFile:1)
	at z0.t.m(SourceFile:1)
	at com.topjohnwu.superuser.ipc.a.c(SourceFile:1)
	at com.topjohnwu.superuser.ipc.a.b(SourceFile:16)
	at com.topjohnwu.superuser.ipc.a.a(SourceFile:1)
	at io.github.reveny.injector.ui.fragment.InjectionFragment.G0(SourceFile:136)
	at G0.e.onClick(SourceFile:48)
	at android.view.View.performClick(View.java:7931)
	at android.view.View.performClickInternal(View.java:7908)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30992)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8594)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14499)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2666)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2844)
	at android.os.Binder.execTransactInternal(Binder.java:1500)
	at android.os.Binder.execTransact(Binder.java:1444)


```

**Comment by reveny** [comment]
This is an issue with outdated libsu. This will be fixed in the next release
